
services: 

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "${NGINX_PORT}:443"
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/cert/:/etc/nginx/cert:ro
    networks:
      - auth_net
      - monitor_net
    depends_on: 
      - authelia
      - grafana
      - httpbin

  authelia:
    container_name: authelia
    image: docker.io/authelia/authelia:latest
    restart: 'unless-stopped'
    networks:
      - auth_net
    environment:
      AUTHELIA_LOG_LEVEL: ${AUTHELIA_LOG_LEVEL}
      AUTHELIA_SERVER_BUFFERS_READ: ${AUTHELIA_SERVER_BUFFERS_READ}
    volumes:
      - '${PWD}/data/authelia/config:/config'
      - '${PWD}/data/authelia/secrets:/secrets'
  
  db:
    image: postgres:16
    container_name: authelia-db
    networks:
      - auth_net
    environment:
      POSTGRES_USER: ${AUTHELIA_DB_USER}
      #POSTGRES_PASSWORD: ${AUTHELIA_DB_PASSWD}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: ${AUTHELIA_DB_NAME}
    volumes:
      - ./data/authelia/secrets/STORAGE_PASSWORD:/run/secrets/db_password:ro
      - postgres_data:/var/lib/postgresql/data

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    pid: host
    networks:
      - monitor_net
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    networks:
      - monitor_net
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - node-exporter

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_AUTH_PROXY_ENABLED=true             # เปิดระบบรับ User จาก Proxy
      - GF_AUTH_PROXY_HEADER_NAME=Remote-User  # บอกว่าชื่อ User อยู่ใน Header ไหน (ต้องตรงกับ Nginx)
      - GF_AUTH_PROXY_HEADER_PROPERTY=username # ให้เอาค่านั้นไปเป็น username
      - GF_AUTH_PROXY_AUTO_SIGN_UP=true       # เปิด auto sing in จาก nginx
      - GF_ANALYTICS_REPORTING_ENABLED=false # ปิดการส่งสถิติการใช้งาน
      - GF_CHECK_FOR_UPDATES=false           # ปิดการเช็คเวอร์ชันใหม่
      - GF_NEWS_FEED_ENABLED=false            # ปิดการดึงข่าวจาก Grafana
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - monitor_net
  httpbin:
    image: kennethreitz/httpbin
    networks:
      - monitor_net

secrets:
  STORAGE_PASSWORD:
    file: ./data/authelia/secrets/STORAGE_PASSWORD

networks:
  auth_net:
    driver: bridge
    internal: false
  monitor_net:
    driver: bridge
    internal: true

volumes:
  postgres_data:
